spring.application.name=backend
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/personlist
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-clas-name=com.mysql.cj.jdbc.Driver


